services:
  db_axum_at:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: axum_at
      POSTGRES_USER: axum
      POSTGRES_PASSWORD: 'mypasswor1235123'
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - ./db_axum_at:/var/lib/postgresql
